services:
  gasolineras-db:
    image: postgres:15-alpine
    container_name: gasolineras-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gasolineras}
    # Sin 'ports:' para no chocar con el 5432 del host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-gasolineras}"]
      interval: 5s
      timeout: 5s
      retries: 10

  gasolineras-api:
    build:
      context: ./    # ajusta si tu backend está en ./app o ./backend
    container_name: gasolineras-api
    depends_on:
      gasolineras-db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gasolineras}
      POSTGRES_HOST: gasolineras-db
      POSTGRES_PORT: "5432"
      # O bien pasa la URL directa:
      # DATABASE_URL: postgresql+psycopg2://postgres:postgres@gasolineras-db:5432/gasolineras
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
